language: clojure
lein: 2.4.0

deploy:
  provider: releases
  api_key: $RELEASES_TOKEN
  file: "resources/stand.scad"
  skip_cleanup: true
  draft: true
  
before_install: sudo apt-get install -y openscad
script: echo "(use 'ergodox-stand.core :reload)" | lein repl
